# Generated by Django 4.0 on 2021-12-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_studentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=17)),
                ('roomfees', models.CharField(max_length=17)),
            ],
        ),
    ]
